[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn routingBeta:app --host 0.0.0.0 --port $PORT"
