"$schema" = "https://railway.com/railway.schema.json"

[build]
builder = "NIXPACKS"
rootDirectory = "backend"
buildCommand = "ln -sf $(which pip3) /usr/local/bin/pip && pip install --upgrade pip && pip install -r requirements.txt"

[build.env]
NIXPACKS_PKGS = "python310Full"

[deploy]
startCommand = "uvicorn routingBeta:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/directions"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"