"$schema" = "https://railway.com/railway.schema.json"

[build]
builder = "NIXPACKS"
rootDirectory = "backend"
buildCommand = """
curl -sSL https://install.python-poetry.org | python3 - && \
export PATH="$HOME/.local/bin:$PATH" && \
poetry install --no-root
"""

[deploy]
startCommand = "poetry run uvicorn routingBeta:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/directions"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
