"$schema" = "https://railway.com/railway.schema.json"

[build]
builder = "NIXPACKS"
rootDirectory = "backend"

[deploy]
startCommand = "uvicorn routingBeta:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/directions"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
