$schema = "https://railway.com/railway.schema.json"

[build]
builder = "NIXPACKS"
buildCommand = """
curl -sSL https://install.python-poetry.org | python3 -
export PATH="$HOME/.local/bin:$PATH"
poetry install --no-root
"""

[deploy]
# Start your backend service on Railway's provided port.
startCommand = "poetry run uvicorn routingBeta:app --host 0.0.0.0 --port $PORT"
# Optionally, you can define a healthcheck path. If you have a /health endpoint, use that.
healthcheckPath = "/api/directions"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
