$schema = "https://railway.com/railway.schema.json"

[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
# Start the Next.js production server.
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ALWAYS"
